// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI0EtNigBpEixu7yFjvJAM6o0Gjyg2h7U',
    appId: '1:233232788861:web:4d8b7b6e8b7eccdb6ff014',
    messagingSenderId: '233232788861',
    projectId: 'firstapp-1091c',
    authDomain: 'firstapp-1091c.firebaseapp.com',
    storageBucket: 'firstapp-1091c.appspot.com',
    measurementId: 'G-HQ3GYX5WZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDQrlDI-p6iea5KArs-Vfb6BF4MwFnvxU',
    appId: '1:233232788861:android:2b76fa779f6cb7146ff014',
    messagingSenderId: '233232788861',
    projectId: 'firstapp-1091c',
    storageBucket: 'firstapp-1091c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsZ5LNZjIo8tdO-n-Xx36pyGlFSEoP1dw',
    appId: '1:233232788861:ios:565f9a2b3a7907fe6ff014',
    messagingSenderId: '233232788861',
    projectId: 'firstapp-1091c',
    storageBucket: 'firstapp-1091c.appspot.com',
    iosBundleId: 'com.abhay.myfirstnotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsZ5LNZjIo8tdO-n-Xx36pyGlFSEoP1dw',
    appId: '1:233232788861:ios:15ffd142ecd5bb816ff014',
    messagingSenderId: '233232788861',
    projectId: 'firstapp-1091c',
    storageBucket: 'firstapp-1091c.appspot.com',
    iosBundleId: 'com.abhay.myfirstnotes.RunnerTests',
  );
}
